machine:
  services:
    - docker
  java:
    version: oraclejdk8

jobs:
  build:
    docker:
    steps:
      - run: echo "Test"
  test:
    steps:
      - run: bash ci/security-checks.sh
  deployment:
    staging:
      branch: master
      heroku:
        appname: circle-ci-test
      steps:
        - run: echo "deploy"

general:
  artifacts:
    - /tmp/artifacts/hawkeye_report.json