machine:
  services:
    - docker
  java:
    version: oraclejdk8

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: echo "Test"
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: bash ci/security-checks.sh
  deployment:
    docker:
      - image: buildpack-deps:trusty
    staging:
      branch: master
      heroku:
        appname: circle-ci-test
    steps:
      - run: echo "deploy"

general:
  artifacts:
    - /tmp/artifacts/hawkeye_report.json